### ISSUE TITLE
Change query port?

### ISSUE THREAD

**Issue by ghost** [MCNewsTools/MCServerStatus-WordPressWidget#7]
I already have my query port set to 8193, as a few of the voting websites have query enabled. Is it possible to have this plugin check 8193 instead? I entered that in the widget config, and I also edited the plugin using the built in editor and replaced 2 instances of the number 25565 with 8193 but it still shows our server as offline.

Any help would be greatly appreciated!

**Comment by GoneTone** [comment]
It is possible that your host does not support the Query protocol.

**Comment by MrAureliusR** [comment]
Well, it works just fine for the voting sites that support it. I'm using Spigot, most recent version. The voting sites that support Query see the server on 8193, and can see online players and plugins.

**Comment by MrAureliusR** [comment]
Tried changing the query port to 25565, still not working. Is there a way to display debug data?

**Comment by MrAureliusR** [comment]
Turns out the issue was with CloudFlare's HTTP proxy. Strange  that some of the voting website seem to have no issue... I think the only different an end user application would see would be the HTTP headers. Not sure why this would affect this plugin!

**Comment by GoneTone** [comment]
Those methods of voting websites seem to be different... I am not sure as well.
